---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha

## comment

workflows:
  version: 2
  test-and-release:
    jobs:
      # - release-management/validate-pr:
      #     filters:
      #       branches:
      #         ignore: master
      # - release-management/test-package:
      #     name: node-latest
      #     node_version: latest
      #     filters:
      #       branches:
      #         only: mdonnalley/data
      # - release-management/test-package:
      #     name: node-12
      - release-management/release-lerna-packages:
          sign: packages/plugin-data
          tag: test
          # requires:
          #   - node-latest
          filters:
            branches:
              only: mdonnalley/data
